_BASE_: "./CLIP_fast_rcnn_R_50_C4_ovd.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 17
DATASETS:
  TRAIN: ("training_class_2_train",)
  TEST: ("training_class_2_val",)
SOLVER:
  IMS_PER_BATCH: 2
  MAX_ITER: 270000
TEST:
  EVAL_PERIOD: 10000